spring:
  application:
    name: sai-backend
  
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/sai_management?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: # 如果有密码请填写
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api

# Swagger/OpenAPI 配置
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    display-operation-id: true
  show-actuator: false
  group-configs:
    - group: 'default'
      display-name: 'SAI Management Platform API'
      paths-to-match: '/**'
      packages-to-scan: 'com.sai.backend.controller'

# 日志配置
logging:
  level:
    com.sai.backend: debug
    org.springframework.security: debug